# Generated by Django 3.1.5 on 2021-01-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_author',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blog_content',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blog_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
