# Generated by Django 3.1.5 on 2021-01-10 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20210110_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostcomment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.blogpost'),
        ),
    ]
