# Generated by Django 3.1.5 on 2021-01-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20210107_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('blog_date',)},
        ),
        migrations.AddField(
            model_name='blogpostcomment',
            name='comment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpostcomment',
            name='comment_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
