# Generated by Django 3.1.5 on 2021-01-08 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20210108_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('blog_date', 'blog_time')},
        ),
    ]
