# Generated by Django 3.1.5 on 2021-01-11 03:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0004_auto_20210110_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
