# Generated by Django 3.1.5 on 2021-01-08 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20210108_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('blog_time', 'blog_date')},
        ),
    ]
