# Generated by Django 3.1.5 on 2021-01-08 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20210108_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('blog_date',)},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='blog_time',
        ),
    ]
